export const PhotoList = [
  {
    url: "/foto/13-min.jpg",
    description: "A scenic view of the mountains.",
    device: "DSLR",
    location: "Swiss Alps",
  },
  {
    url: "/foto/20-min.jpg",
    description: "Sunset at the beach.",
    device: "iPhone",
    location: "Malibu Beach",
  },
  {
    url: "/foto/23-min.jpg",
    description: "A close-up of a flower.",
    device: "Samsung Galaxy",
    location: "Botanical Garden",
  },
  {
    url: "/foto/32-min.jpg",
    description: "A busy city street at night.",
    device: "Canon",
    location: "New York City",
  },
  {
    url: "/foto/35-min.jpg",
    description: "A portrait of a woman.",
    device: "Nikon",
    location: "Paris, France",
  },
  {
    url: "/foto/36-min.jpg",
    description: "A panoramic shot of the desert.",
    device: "GoPro",
    location: "Sahara Desert",
  },
  {
    url: "/foto/38-min.jpg",
    description: "A forest trail in autumn.",
    device: "Sony Alpha",
    location: "Black Forest, Germany",
  },
  {
    url: "/foto/35-min.jpg",
    description: "A portrait of a woman.",
    device: "Nikon",
    location: "Paris, France",
  },
  {
    url: "/foto/36-min.jpg",
    description: "A panoramic shot of the desert.",
    device: "GoPro",
    location: "Sahara Desert",
  },
  {
    url: "/foto/38-min.jpg",
    description: "A forest trail in autumn.",
    device: "Sony Alpha",
    location: "Black Forest, Germany",
  },
  {
    url: "/foto/13-min.jpg",
    description: "A scenic view of the mountains.",
    device: "DSLR",
    location: "Swiss Alps",
  },
  {
    url: "/foto/20-min.jpg",
    description: "Sunset at the beach.",
    device: "iPhone",
    location: "Malibu Beach",
  },
  {
    url: "/foto/23-min.jpg",
    description: "A close-up of a flower.",
    device: "Samsung Galaxy",
    location: "Botanical Garden",
  },
];
